require 'rake/testtask'
require 'warbler'

Maven = Struct.new(:groupId, :artifactId, :version)
maven = Maven.new('otpp.devdays', 'com.otpp.devdays.careerevent.CareerEventDomain', '1.0.0-SNAPSHOT')
jarfile = "#{maven.artifactId}-#{maven.version}.jar"

task :default => [:clean, :install]

desc 'Cleans compiled code'
task :clean do
  puts "Cleaning..."
  rm_rf 'target'
end

Rake::TestTask.new do |t|
  puts "Testing..."
  t.pattern = "test/*.rb"
end

Warbler::Task.new

desc 'Compiles all JRuby code in src and packages it as a jar file'
task :package => [:test, :jar] do
  puts "Packaging..."

  mkdir_p 'target'
  # Get the Java classpath from jbundler
  system "mv CewsDomain.jar target/#{jarfile}"
  system "rm -rf com"
end

desc 'Use Maven to install the generated jar to the local .m2'
task :install => [:package] do
  puts "Installing..."
  system "mvn install:install-file -Dfile=target/#{jarfile} -DgroupId=#{maven.groupId} -DartifactId=#{maven.artifactId} -Dversion=#{maven.version} -Dpackaging=jar"
end
