require 'rake/testtask'

Maven = Struct.new(:groupId, :artifactId, :version)
maven = Maven.new('otpp.careerevent', 'com.otpp.careerevent.CareerEventManager', '1.0.0-SNAPSHOT')
jarfile = "#{maven.artifactId}-#{maven.version}.jar"

task :default => [:clean, :install]

desc 'Cleans compiled code'
task :clean do
  puts "Cleaning..."
  rm_rf 'target'
end

Rake::TestTask.new do |t|
  puts "Testing..."
  t.pattern = "test/*.rb"
end

desc 'Compiles all JRuby code in src and packages it as a jar file'
task :package => [:test] do
  puts "Packaging..."

  # Get the Java classpath from jbundler
  require '.jbundler/classpath.rb'
  classpath = JBUNDLER_CLASSPATH.join ':'

  mkdir_p 'target/classes'
  system "jrubyc --javac -5 -c #{classpath} src -t target/classes"
  system "jar cf target/#{jarfile} -C target/classes ."
end

desc 'Use Maven to install the generated jar to the local .m2'
task :install => [:package] do
  puts "Installing..."
  system "mvn install:install-file -Dfile=target/#{jarfile} -DgroupId=#{maven.groupId} -DartifactId=#{maven.artifactId} -Dversion=#{maven.version} -Dpackaging=jar"
end
